import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export function TokenMetrics({ metrics }) {
    const savingsPercent = metrics.token_savings_percent;
    const progressWidth = Math.min(Math.max(savingsPercent, 0), 100);
    return (_jsxs("div", { className: "rounded-lg border border-gray-200 bg-white p-4", children: [_jsx("h3", { className: "mb-3 text-sm font-semibold text-gray-700", children: "Token Savings" }), _jsxs("div", { className: "mb-3", children: [_jsxs("div", { className: "flex items-center justify-between text-xs text-gray-500 mb-1", children: [_jsx("span", { children: "Reduction" }), _jsxs("span", { className: "font-medium text-green-600", children: [savingsPercent.toFixed(1), "%"] })] }), _jsx("div", { className: "h-3 rounded-full bg-gray-100 overflow-hidden", children: _jsx("div", { className: "h-full rounded-full bg-gradient-to-r from-green-400 to-green-600 transition-all duration-500", style: { width: `${progressWidth}%` } }) })] }), _jsxs("div", { className: "grid grid-cols-2 gap-3 mb-3", children: [_jsxs("div", { className: "rounded bg-gray-50 p-2", children: [_jsx("div", { className: "text-xs text-gray-500", children: "Original" }), _jsx("div", { className: "text-lg font-semibold text-gray-700", children: metrics.original_tokens.toLocaleString() })] }), _jsxs("div", { className: "rounded bg-green-50 p-2", children: [_jsx("div", { className: "text-xs text-gray-500", children: "Optimized" }), _jsx("div", { className: "text-lg font-semibold text-green-700", children: metrics.optimized_tokens.toLocaleString() })] })] }), _jsxs("div", { className: "flex items-center justify-between rounded bg-blue-50 p-2 mb-3", children: [_jsx("span", { className: "text-xs text-gray-600", children: "Tokens saved" }), _jsx("span", { className: "font-medium text-blue-700", children: (metrics.original_tokens - metrics.optimized_tokens).toLocaleString() })] }), _jsxs("div", { className: "flex items-center gap-2 text-xs", children: [_jsx("span", { className: "text-gray-500", children: "Cache:" }), metrics.cache_hit ? (_jsxs("span", { className: "flex items-center gap-1 text-green-600", children: [_jsx("svg", { className: "w-4 h-4", fill: "currentColor", viewBox: "0 0 20 20", children: _jsx("path", { fillRule: "evenodd", d: "M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z", clipRule: "evenodd" }) }), "HIT (", metrics.cache_read_tokens.toLocaleString(), " tokens)"] })) : (_jsx("span", { className: "text-gray-400", children: metrics.cache_creation_tokens > 0
                            ? `WRITE (${metrics.cache_creation_tokens.toLocaleString()} tokens)`
                            : "MISS" }))] }), _jsxs("div", { className: "mt-3 pt-3 border-t border-gray-100 text-xs text-gray-400", children: [_jsxs("span", { children: ["Max tables: ", metrics.max_tables_setting] }), _jsx("span", { className: "mx-2", children: "|" }), _jsxs("span", { children: ["Min score: ", metrics.min_score_setting] })] })] }));
}
export function TableList({ included, skipped, total }) {
    return (_jsxs("div", { className: "rounded-lg border border-gray-200 bg-white p-4", children: [_jsxs("h3", { className: "mb-3 text-sm font-semibold text-gray-700", children: ["Tables (", included.length, "/", total, ")"] }), _jsxs("div", { className: "mb-3", children: [_jsx("div", { className: "text-xs text-gray-500 mb-1", children: "Included" }), _jsx("div", { className: "flex flex-wrap gap-1", children: included.map((t) => (_jsxs("span", { className: "inline-flex items-center gap-1 rounded bg-green-50 px-2 py-0.5 text-xs text-green-700", children: [_jsx("svg", { className: "w-3 h-3", fill: "currentColor", viewBox: "0 0 20 20", children: _jsx("path", { fillRule: "evenodd", d: "M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z", clipRule: "evenodd" }) }), t] }, t))) })] }), skipped.length > 0 && (_jsxs("div", { children: [_jsxs("div", { className: "text-xs text-gray-500 mb-1", children: ["Skipped (", skipped.length, ")"] }), _jsx("div", { className: "flex flex-wrap gap-1 max-h-24 overflow-y-auto", children: skipped.map((t) => (_jsxs("span", { className: "inline-flex items-center gap-1 rounded bg-gray-100 px-2 py-0.5 text-xs text-gray-500", children: [_jsx("svg", { className: "w-3 h-3", fill: "currentColor", viewBox: "0 0 20 20", children: _jsx("path", { fillRule: "evenodd", d: "M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z", clipRule: "evenodd" }) }), t] }, t))) })] }))] }));
}
